### PR TITLE
Cigar and md changes

### LINKED ISSUE #40: Segfault in certain situations involving cigar
It appears that in certain situations interacting with the cigar can lead to a segfault. I experienced this in ldc 1.20, only when building in release mode.
```
foreach (SAMRecord read; bam.all_records)
{
    /// do something with record
    Cigar cigar = read.cigar;
    auto cigar_ops = cigar.ops; //cigar.ops is a slice to the original cigar data 
    
    /// SAMRecord reaped here?
    /// do something with cigar_ops -> segfault
}
```
Sometimes in the above situation, I think the SAMRecord will be reaped before we are done using the cigar data. The cigar is simply a slice to the data allocated by htslib to the cigar array. The easy fix for this is below; we simply duplicate the cigar before use.
```
auto cigar_ops = cigar.ops.dup;
```
Potentially we should modify the ```cigar()``` method in ```SAMRecord``` to always duplicate the original cigar data rather than return a slice.

### PR DESCRIPTION
**Pull request by charlesgregory**
Pull request for discussion of changes.
```md.d``` and ```cigar.d``` pulled under ```dhtslib.sam```
Can now use ```opIndex``` and ```opSlice``` for indexing and assignment with ```Cigar``` struct directly.
Should fix #40 by adding dups in ctors. If ctor is used, Cigar struct should own the cigar string data.
Any other changes to be made?

### CODE REVIEW

File: source/dhtslib/sam/cigar.d [hunk 1]
```diff
@@ -24,13 +24,13 @@ struct Cigar
     /// Construct Cigar from raw data
     this(uint* cigar, uint length)
     {
-        ops = (cast(CigarOp*) cigar)[0 .. length];
+        ops = (cast(CigarOp*) cigar)[0 .. length].dup;
```
Comment (jblachly) [inline source/dhtslib/sam/cigar.d:28]: Cigar stuff is likely called from hot loops; do you think this will have a negative impact on speed of client code? Certainly we have to address the segfault issue, but I wonder what other solutions may be possible? If segfault is due to GC, options could be limited. Same comment applies to the other constructor `.dup`

Comment (jblachly) [reply source/dhtslib/sam/cigar.d:28]: R eplying to myself. If Dlang used a reference counting GC we wouldn't have this problem, if it is what I think it is (i.e. the read data to which the cigar data are pointing being freed)

**Review by jblachly — COMMENTED** [review]
Can the indexing overloads be exercised with test cases?

**Comment by jblachly** [comment]
1. Thanks for tackling this
2. I should have set up CI and coverage a loooong time ago
    - note that the testing caught the error that needed to be fixed wtih the 4th commit

General comments:


> Can the indexing overloads be exercised with test cases?

Oh, scratch that, I see the next commit, and coverage report confirms

File: source/dhtslib/sam/md.d [hunk 2]
```diff
@@ -152,7 +152,7 @@ debug (dhtslib_unittest) unittest
     import std.array : array;
     import std.path : buildPath, dirName;
 
-    auto bam = SAMFile(buildPath(dirName(dirName(dirName(__FILE__))), "htslib",
+    auto bam = SAMFile(buildPath(dirName(dirName(dirName(dirName(__FILE__)))), "htslib",
```
Comment (jblachly) [inline source/dhtslib/sam/md.d:155]: You don't need to chagne this at this time (I am planning to extract and separate "integration tests" from "unit tests" at some point in the future), but I would instead of parent, parent, parent of __FILE__ (which could as it does in this commit, change location), just use cwd of the test binary which has `htslib` subdir as its immediate child

File: source/dhtslib/sam/cigar.d (hunk 1 above)
Comment (charlesgregory) [reply source/dhtslib/sam/cigar.d:28]: So this is to solve situations where the GC reaps the SAM record but the cigar is continuing to be used. This can happen if you're just doing cigar manipulation with the SAM record. GC is aggressive and doesn't wait for the SAM record to go out of scope since it is no longer being used. I certainly think the dup will affect performance negatively. I would prefer a solution that instead prevents reaping of SAM Record if there is still a reference to the backing bam1_t data. Maybe GC.addRange could help? I would like a better solution.

**Comment by charlesgregory** [comment]
> Should we continue to make available dhtslib.cigar and dhtslib.sam so as not to break client code? Probably fishnet, the error correction software, and other client code are going to have to be updated unless we do, but it will also clutter the namespace. Feel free to say "no" as we haven't done a public dhtslib release yet and only our code depends. should be easy to find and fix with a regex across codebases

Since dlang tends to be good about versioning its packages I would say no. It can be up to the programmer to update their code for api changes.

File: source/dhtslib/sam/cigar.d (hunk 1 above)
Comment (jblachly) [reply source/dhtslib/sam/cigar.d:28]: Yes, GC.addRange or addRoot could help (although those calls might also slow things down, not sure about compared to a small string dup). Another solution is to disable GC in loops iterating over sam files which would speed things up evn irrespective of this cigar issue. Nevertheless, can you remind me when it might come up that one has a handle/ptr to the CIGAR data but have lost it to the backing SAMRecord? I am surprised that could happen

Comment (charlesgregory) [reply source/dhtslib/sam/cigar.d:28]:
```
foreach (SAMRecord read; bam.all_records)
{
    /// do something with record
    Cigar cigar = read.cigar;
    auto cigar_ops = cigar.ops; //cigar.ops is a slice to the original cigar data 
    
    /// SAMRecord no longer used
    /// SAMRecord reaped here
    /// do something with cigar_ops -> segfault
}
```

Since Cigar is just a wrapper around the backing cigar ops array, we previously just took a slice from the backing htslib bam variable data that contains the cigar ops. If the ```SAMRecord``` is reaped ever and the ```Cigar``` is not, the cigar's data is invalid. Hence the need for ```Cigar``` to have a copy of the cigar ops data.

Comment (jblachly) [reply source/dhtslib/sam/cigar.d:28]: OK. Let me think about this for a couple of days. Probably over thinking it as many solutions may be as or more expensive than the .dup anyway.

Comment (charlesgregory) [reply source/dhtslib/sam/cigar.d:28]: Though it is worth considering we could have this issue with any parts of dhtslib involving the sam record variable data, potentially our bam tags interface. I usually attempt to provide slices to existing data, rather than making copies for performance sake. We could potentially convert the variable length data of a bam record into proper slices so the GC has more control and notice. This could help the GC "see" when we make a slice to the variable length data and potentially provide more memory safety.

**Comment by charlesgregory** [comment]
So I have removed the dup fixes in cigar as that doesn't truly fix the issue of a cigar potentially having access to free'd ```bam1_t``` data. Current plan is using reference counting on both ```SAMRecord``` and ```Cigar```. ```Cigar``` will have a method that allows one to check its current reference count. ```SAMRecord``` then has a private ```Cigar``` that it will pass out via ```cigar()``` method. Once both the private ```Cigar``` and ```SAMRecord``` have reference counts of 0 the backing ```bam1_t``` can be free'd. Though this may be held up by #57. Any thoughts or concerns?

**Comment by jblachly** [comment]
> So I have removed the dup fixes in cigar as that doesn't truly fix the issue of a cigar potentially having access to free'd `bam1_t` data. Current plan is using reference counting on both `SAMRecord` and `Cigar`. `Cigar` will have a method that allows one to check its current reference count. `SAMRecord` then has a private `Cigar` that it will pass out via `cigar()` method. Once both the private `Cigar` and `SAMRecord` have reference counts of 0 the backing `bam1_t` can be free'd. Though this may be held up by #57. Any thoughts or concerns?

Hmm. I hate to couple them so tightly. We could really just discourage the constructor that takes the pointer and rely on the consumer to be an expert to use this when you know you won't have a use-after-free problem. There is an alternative constructor that takes a dynamic array or slice that could be favored in other cases.

I can accept this PR as is

**Comment by charlesgregory** [comment]
After we fix #57, I can make another pull request to further hash the issue of reference counting and ownership.
